services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    init: true
    container_name: server
    ports:
      - "8081:8080"
    volumes:
      - ./backups:/backup
    networks:
      - my_net
    env_file:
      - environment

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    init: true
    container_name: client
    ports:
      - "8082:8080"
    volumes:
      - ./logs:/log
    networks:
      - my_net
    env_file:
      - environment

networks:
  my_net:
    driver: bridge
