services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=prod
    init: true
    container_name: server
    # entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./backups:/backup
    env_file:
      - environment

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=prod
    init: true
    container_name: client
    # entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./logs:/log
    env_file:
      - environment
